
menu:
  Home: /
  Archives: /archives
  About: /about

widgets: 
- search
- category
- weibo

excerpt_link: Read More

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true


fancybox: true

google_analytics:
rss: